// Check if content_vector trigger exists
require('dotenv').config({ path: './backend/.env' });
const { Pool } = require('pg');

async function checkTrigger() {
  const pool = new Pool({
    user: process.env.PG_USER,
    host: process.env.PG_HOST,
    database: process.env.PG_DATABASE,
    password: process.env.PG_PASSWORD,
    port: parseInt(process.env.PG_PORT) || 5432,
    ssl: false
  });

  try {
    console.log('🔍 Checking triggers on repo_data table\n');

    const result = await pool.query(`
      SELECT 
        trigger_name,
        event_manipulation,
        action_statement
      FROM information_schema.triggers
      WHERE event_object_table = 'repo_data'
      ORDER BY trigger_name
    `);
    
    if (result.rows.length > 0) {
      console.log('📋 Triggers found:');
      result.rows.forEach(r => {
        console.log(`  - ${r.trigger_name}`);
        console.log(`    Event: ${r.event_manipulation}`);
        console.log(`    Action: ${r.action_statement}\n`);
      });
    } else {
      console.log('⚠️  NO TRIGGERS FOUND on repo_data table!');
      console.log('\n💡 The content_vector column should be auto-generated by a trigger.');
      console.log('   This trigger needs to be created to enable full-text search.');
    }
    
  } catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

checkTrigger();
